import { Component, OnInit } from '@angular/core';
import {RandomThingList} from "./RandomThingList";
import {MythicalCreatures} from "./MythicalCreatures";

@Component({
  selector: 'inspiration-randomizer',
  templateUrl: './inspiration-randomizer.component.html',
  styleUrls: ['./inspiration-randomizer.component.scss']
})
export class InspirationRandomizerComponent implements OnInit {

  animals = [
    'Canidae',
    'Felidae',
    'Cat',
    'Cattle',
    'Dog',
    'Donkey',
    'Goat',
    'Guinea pig',
    'Horse',
    'Pig',
    'Rabbit',
    'Fancy rat varieties',
    'laboratory rat strains',
    'Sheep breeds',
    'Water buffalo breeds',
    'Chicken breeds',
    'Duck breeds',
    'Goose breeds',
    'Pigeon breeds',
    'Turkey breeds',
    'Aardvark',
    'Aardwolf',
    'African buffalo',
    'African elephant',
    'African leopard',
    'Albatross',
    'Alligator',
    'Alpaca',
    'American buffalo (bison)',
    'American robin',
    'Amphibian',
    'list',
    'Anaconda',
    'Angelfish',
    'Anglerfish',
    'Ant',
    'Anteater',
    'Antelope',
    'Antlion',
    'Ape',
    'Aphid',
    'Arabian leopard',
    'Arctic Fox',
    'Arctic Wolf',
    'Armadillo',
    'Arrow crab',
    'Asp',
    'Ass (donkey)',
    'Baboon',
    'Badger',
    'Bald eagle',
    'Bandicoot',
    'Barnacle',
    'Barracuda',
    'Basilisk',
    'Bass',
    'Bat',
    'Beaked whale',
    'Bear',
    'list',
    'Beaver',
    'Bedbug',
    'Bee',
    'Beetle',
    'Bird',
    'list',
    'Bison',
    'Blackbird',
    'Black panther',
    'Black widow spider',
    'Blue bird',
    'Blue jay',
    'Blue whale',
    'Boa',
    'Boar',
    'Bobcat',
    'Bobolink',
    'Bonobo',
    'Booby',
    'Box jellyfish',
    'Bovid',
    'Buffalo, African',
    'Buffalo, American (bison)',
    'Bug',
    'Butterfly',
    'Buzzard',
    'Camel',
    'Canid',
    'Cape buffalo',
    'Capybara',
    'Cardinal',
    'Caribou',
    'Carp',
    'Cat',
    'list',
    'Catshark',
    'Caterpillar',
    'Catfish',
    'Cattle',
    'list',
    'Centipede',
    'Cephalopod',
    'Chameleon',
    'Cheetah',
    'Chickadee',
    'Chicken',
    'list',
    'Chimpanzee',
    'Chinchilla',
    'Chipmunk',
    'Clam',
    'Clownfish',
    'Cobra',
    'Cockroach',
    'Cod',
    'Condor',
    'Constrictor',
    'Coral',
    'Cougar',
    'Cow',
    'Coyote',
    'Crab',
    'Crane',
    'Crane fly',
    'Crawdad',
    'Crayfish',
    'Cricket',
    'Crocodile',
    'Crow',
    'Cuckoo',
    'Cicada',
    'Damselfly',
    'Deer',
    'Dingo',
    'Dinosaur',
    'list',
    'Dog',
    'list',
    'Dolphin',
    'Donkey',
    'list',
    'Dormouse',
    'Dove',
    'Dragonfly',
    'Dragon',
    'Duck',
    'list',
    'Dung beetle',
    'Eagle',
    'Earthworm',
    'Earwig',
    'Echidna',
    'Eel',
    'Egret',
    'Elephant',
    'Elephant seal',
    'Elk',
    'Emu',
    'English pointer',
    'Ermine',
    'Falcon',
    'Ferret',
    'Finch',
    'Firefly',
    'Fish',
    'Flamingo',
    'Flea',
    'Fly',
    'Flyingfish',
    'Fowl',
    'Fox',
    'Frog',
    'Fruit bat',
    'Gamefowl',
    'list',
    'Galliform',
    'list',
    'Gazelle',
    'Gecko',
    'Gerbil',
    'Giant panda',
    'Giant squid',
    'Gibbon',
    'Gila monster',
    'Giraffe',
    'Goat',
    'list',
    'Goldfish',
    'Goose',
    'list',
    'Gopher',
    'Gorilla',
    'Grasshopper',
    'Great blue heron',
    'Great white shark',
    'Grizzly bear',
    'Ground shark',
    'Ground sloth',
    'Grouse',
    'Guan',
    'list',
    'Guanaco',
    'Guineafowl',
    'list',
    'Guinea pig',
    'list',
    'Gull',
    'Guppy',
    'Haddock',
    'Halibut',
    'Hammerhead shark',
    'Hamster',
    'Hare',
    'Harrier',
    'Hawk',
    'Hedgehog',
    'Hermit crab',
    'Heron',
    'Herring',
    'Hippopotamus',
    'Hookworm',
    'Hornet',
    'Horse',
    'list',
    'Hoverfly',
    'Hummingbird',
    'Humpback whale',
    'Hyena',
    'Iguana',
    'Impala',
    'Irukandji jellyfish',
    'Jackal',
    'Jaguar',
    'Jay',
    'Jellyfish',
    'Junglefowl',
    'Kangaroo',
    'Kangaroo mouse',
    'Kangaroo rat',
    'Kingfisher',
    'Kite',
    'Kiwi',
    'Koala',
    'Koi',
    'Komodo dragon',
    'Krill',
    'Ladybug',
    'Lamprey',
    'Landfowl',
    'Land snail',
    'Lark',
    'Leech',
    'Lemming',
    'Lemur',
    'Leopard',
    'Leopon',
    'Limpet',
    'Lion',
    'Lizard',
    'Llama',
    'Lobster',
    'Locust',
    'Loon',
    'Louse',
    'Lungfish',
    'Lynx',
    'Macaw',
    'Mackerel',
    'Magpie',
    'Mammal',
    'Manatee',
    'Mandrill',
    'Manta ray',
    'Marlin',
    'Marmoset',
    'Marmot',
    'Marsupial',
    'Marten',
    'Mastodon',
    'Meadowlark',
    'Meerkat',
    'Mink',
    'Minnow',
    'Mite',
    'Mockingbird',
    'Mole',
    'Mollusk',
    'Mongoose',
    'Monitor lizard',
    'Monkey',
    'Moose',
    'Mosquito',
    'Moth',
    'Mountain goat',
    'Mouse',
    'Mule',
    'Muskox',
    'Narwhal',
    'Newt',
    'New World quail',
    'Nightingale',
    'Ocelot',
    'Octopus',
    'Old World quail',
    'Opossum',
    'Orangutan',
    'Orca',
    'Ostrich',
    'Otter',
    'Owl',
    'Ox',
    'Panda',
    'Panther',
    'Panthera hybrid',
    'Parakeet',
    'Parrot',
    'Parrotfish',
    'Partridge',
    'Peacock',
    'Peafowl',
    'Pelican',
    'Penguin',
    'Perch',
    'Peregrine falcon',
    'Pheasant',
    'Pig',
    'Pigeon',
    'list',
    'Pike',
    'Pilot whale',
    'Pinniped',
    'Piranha',
    'Planarian',
    'Platypus',
    'Polar bear',
    'Pony',
    'Porcupine',
    'Porpoise',
    'Portuguese man o\' war',
    'Possum',
    'Prairie dog',
    'Prawn',
    'Praying mantis',
    'Primate',
    'Ptarmigan',
    'Puffin',
    'Puma',
    'Python',
    'Quail',
    'Quelea',
    'Quokka',
    'Rabbit',
    'list',
    'Raccoon',
    'Rainbow trout',
    'Rat',
    'Rattlesnake',
    'Raven',
    'Ray (Batoidea)',
    'Ray (Rajiformes)',
    'Red panda',
    'Reindeer',
    'Reptile',
    'Rhinoceros',
    'Right whale',
    'Roadrunner',
    'Rodent',
    'Rook',
    'Rooster',
    'Roundworm',
    'Saber-toothed cat',
    'Sailfish',
    'Salamander',
    'Salmon',
    'Sawfish',
    'Scale insect',
    'Scallop',
    'Scorpion',
    'Seahorse',
    'Sea lion',
    'Sea slug',
    'Sea snail',
    'Shark',
    'list',
    'Sheep',
    'list',
    'Shrew',
    'Shrimp',
    'Silkworm',
    'Silverfish',
    'Skink',
    'Skunk',
    'Sloth',
    'Slug',
    'Smelt',
    'Snail',
    'Snake',
    'list',
    'Snipe',
    'Snow leopard',
    'Sockeye salmon',
    'Sole',
    'Sparrow',
    'Sperm whale',
    'Spider',
    'Spider monkey',
    'Spoonbill',
    'Squid',
    'Squirrel',
    'Starfish',
    'Star-nosed mole',
    'Steelhead trout',
    'Stingray',
    'Stoat',
    'Stork',
    'Sturgeon',
    'Sugar glider',
    'Swallow',
    'Swan',
    'Swift',
    'Swordfish',
    'Swordtail',
    'Tahr',
    'Takin',
    'Tapir',
    'Tarantula',
    'Tarsier',
    'Tasmanian devil',
    'Termite',
    'Tern',
    'Thrush',
    'Tick',
    'Tiger',
    'Tiger shark',
    'Tiglon',
    'Toad',
    'Tortoise',
    'Toucan',
    'Trapdoor spider',
    'Tree frog',
    'Trout',
    'Tuna',
    'Turkey',
    'list',
    'Turtle',
    'Tyrannosaurus',
    'Urial',
    'Vampire bat',
    'Vampire squid',
    'Vicuna',
    'Viper',
    'Vole',
    'Vulture',
    'Wallaby',
    'Walrus',
    'Wasp',
    'Warbler',
    'Water Boa',
    'Water buffalo',
    'Weasel',
    'Whale',
    'Whippet',
    'Whitefish',
    'Whooping crane',
    'Wildcat',
    'Wildebeest',
    'Wildfowl',
    'Wolf',
    'Wolverine',
    'Wombat',
    'Woodpecker',
    'Worm',
    'Wren',
    'Xerinae',
    'X-ray fish',
    'Yak',
    'Yellow perch',
    'Zebra',
    'Zebra finch',
    'Animals by number of neurons',
    'Animals by size',
    'Common household pests',
    'Common names of poisonous animals',
    'Alpaca',
    'Bali cattle',
    'Cat',
    'Cattle',
    'Chicken',
    'Dog',
    'Domestic Bactrian camel',
    'Domestic canary',
    'Domestic dromedary camel',
    'Domestic duck',
    'Domestic goat',
    'Domestic goose',
    'Domestic guineafowl',
    'Domestic hedgehog',
    'Domestic pig',
    'Domestic pigeon',
    'Domestic rabbit',
    'Domestic silkmoth',
    'Domestic silver fox',
    'Domestic turkey',
    'Donkey',
    'Fancy mouse',
    'Fancy rat',
    'Lab rat',
    'Ferret',
    'Gayal',
    'Goldfish',
    'Guinea pig',
    'Guppy',
    'Horse',
    'Koi',
    'Llama',
    'Ringneck dove',
    'Sheep',
    'Siamese fighting fish',
    'Society finch',
    'Yak',
    'Water buffalo',
  ];

  foods = [
    'legumes',
    'fruit',

    'vegetables',
    'Broccoflower',
    'Cauliflower',
    'Broccoli',
    'Tomatillo',
    'Physalis',
    'Herbs',
    'Spices',
    'Chilli Pepper',
    'Bell Pepper',
    'Potato',
    'Yam',
    'Zuccini',
    'Pumpkin',
    'Asparagus',
    'Carrots',
    'Turnips',
    'Beets',
    'Tomatoes',
    'Artichoke',
    'fennel',
    'celery',
    'brussel sprouts',
    'Okra',
    'Onions',
    'Radicchio',
    'ginger',
    'rhubarb',
    'chestnut',
    'corn',
    'spinach',
    'sassafras',

    'fungi',
    'nuts',
    'baked good',
    'bread',
    'dairy',
    'cheese',
    'meat',
    'sausages',
    'eggs',
    'cereal',
    'rice',
    'seafood',
    'confections',
    'desserts',
    'canned goods',
    'dried foods',
    'dumplings',
    'fast food',
    'Noodles',
    'Sandwiches',
    'Salad',
    'Pie',
    'Stew',
    'Curry',
    'Chocolate bar',
    'Jack fruit',
    'Surströmming',
    'Hákarl'
  ]

  dinosaurs = [

    'Aardonyx',
    'Abelisaurus',
    'Abrictosaurus',
    'Abrosaurus',
    'Abydosaurus',
    'Acanthopholis',
    'Achelousaurus',
    'Achillobator',
    'Acristavus',
    'Acrocanthosaurus',
    'Acrotholus',
    'Adamantisaurus',
    'Adasaurus',
    'Adeopapposaurus',
    'Aegyptosaurus',
    'Aeolosaurus',
    'Aerosteon',
    'Afrovenator',
    'Agathaumas',
    'Agilisaurus',
    'Agujaceratops',
    'Agustinia',
    'Ajkaceratops',
    'Alamosaurus',
    'Alaskacephale',
    'Albalophosaurus',
    'Albertaceratops',
    'Albertadromeus',
    'Albertonykus',
    'Albertosaurus',
    'Alectrosaurus',
    'Aletopelta',
    'Alioramus',
    'Allosaurus',
    'Altirhinus',
    'Alvarezsaurus',
    'Alwalkeria',
    'Alxasaurus',
    'Amargasaurus',
    'Amazonsaurus',
    'Ammosaurus',
    'Ampelosaurus',
    'Amphicoelias',
    'Amurosaurus',
    'Anabisetia',
    'Anatosaurus',
    'Anatotitan',
    'Anchiceratops',
    'Anchiornis',
    'Anchisaurus',
    'Andesaurus',
    'Angaturama',
    'Angolatitan',
    'Angulomastacator',
    'Animantarx',
    'Ankylosaurus',
    'Anodontosaurus',
    'Anserimimus',
    'Antarctopelta',
    'Antarctosaurus',
    'Antetonitrus',
    'Anzu',
    'Aorun',
    'Apatosaurus',
    'Appalachiosaurus',
    'Aquilops',
    'Aragosaurus',
    'Aralosaurus',
    'Archaeoceratops',
    'Archaeopteryx',
    'Archaeornithomimus',
    'Arcovenator',
    'Arcusaurus',
    'Argentinosaurus',
    'Argyrosaurus',
    'Aristosuchus',
    'Arrhinoceratops',
    'Astrodon',
    'Asylosaurus',
    'Atlasaurus',
    'Atlascopcosaurus',
    'Atrociraptor',
    'Aublysodon',
    'Aucasaurus',
    'Auroraceratops',
    'Australodocus',
    'Australovenator',
    'Austroraptor',
    'Austrosaurus',
    'Avaceratops',
    'Aviatyrannis',
    'Avimimus',

    'Bactrosaurus',
    'Bagaceratops',
    'Bagaraatan',
    'Bahariasaurus',
    'Balaur',
    'Bambiraptor',
    'Barapasaurus',
    'Barilium',
    'Barosaurus',
    'Barsboldia',
    'Baryonyx',
    'Batyrosaurus',
    'Becklespinax',
    'Beipiaosaurus',
    'Beishanlong',
    'Bellusaurus',
    'Berberosaurus',
    'Bicentenaria',
    'Bistahieversor',
    'Bonapartenykus',
    'Bonitasaura',
    'Borogovia',
    'Bothriospondylus',
    'Brachiosaurus',
    'Brachyceratops',
    'Brachylophosaurus',
    'Brachytrachelopan',
    'Bravoceratops',
    'Brontomerus',
    'Bruhathkayosaurus',
    'Buitreraptor',
    'Byronosaurus',

    'Camarasaurus',
    'Camarillasaurus',
    'Camelotia',
    'Camptosaurus',
    'Carcharodontosaurus',
    'Carnotaurus',
    'Caudipteryx',
    'Centrosaurus',
    'Cerasinops',
    'Ceratonykus',
    'Ceratosaurus',
    'Cetiosauriscus',
    'Cetiosaurus',
    'Changyuraptor',
    'Chaoyangsaurus',
    'Charonosaurus',
    'Chasmosaurus',
    'Chialingosaurus',
    'Chilantaisaurus',
    'Chilesaurus',
    'Chindesaurus',
    'Chirostenotes',
    'Chubutisaurus',
    'Chungkingosaurus',
    'Citipati',
    'Claosaurus',
    'Coahuilaceratops',
    'Coelophysis',
    'Coelurus',
    'Colepiocephale',
    'Compsognathus',
    'Concavenator',
    'Conchoraptor',
    'Condorraptor',
    'Coronosaurus',
    'Corythosaurus',
    'Crichtonsaurus',
    'Cruxicheiros',
    'Cryolophosaurus',

    'Cryptovolans',
    'Cumnoria',

    'Dacentrurus',
    'Daemonosaurus',
    'Dahalokely',
    'Dakotaraptor',
    'Daspletosaurus',
    'Datousaurus',
    'Darwinsaurus',
    'Deinocheirus',
    'Deinodon',
    'Deinonychus',
    'Delapparentia',
    'Deltadromeus',
    'Demandasaurus',
    'Diabloceratops',
    'Diamantinasaurus',
    'Diceratops',
    'Dicraeosaurus',
    'Dilong',
    'Dilophosaurus',
    'Dimetrodon',
    'Diplodocus',
    'Dollodon',
    'Draconyx',
    'Dracopelta',
    'Dracorex',
    'Dracovenator',
    'Dravidosaurus',
    'Dreadnoughtus',
    'Drinker',
    'Dromaeosauroides',
    'Dromaeosaurus',
    'Dromiceiomimus',
    'Dryosaurus',
    'Dryptosaurus',
    'Dubreuillosaurus',
    'Duriavenator',
    'Dyoplosaurus',
    'Dysalotosaurus',
    'Dyslocosaurus',
    'Dystrophaeus',

    'Echinodon',
    'Edmarka',
    'Edmontonia',
    'Edmontosaurus',
    'Efraasia',
    'Einiosaurus',
    'Ekrixinatosaurus',
    'Elaphrosaurus',
    'Elmisaurus',
    'Elopteryx',
    'Elrhazosaurus',
    'Enigmosaurus',
    'Eoabelisaurus',
    'Eobrontosaurus',
    'Eocarcharia',
    'Eocursor',
    'Eodromaeus',
    'Eolambia',
    'Eoraptor',
    'Eosinopteryx',
    'Eotriceratops',
    'Eotyrannus',
    'Epachthosaurus',
    'Epidendrosaurus',
    'Epidexipteryx',
    'Equijubus',
    'Erectopus',
    'Erketu',
    'Erliansaurus',
    'Erlikosaurus',
    'Euhelopus',
    'Euoplocephalus',
    'Europasaurus',
    'Europelta',
    'Euskelosaurus',
    'Eustreptospondylus',

    'Fabrosaurus',
    'Falcarius',
    'Ferganasaurus',
    'Fruitadens',
    'Fukuiraptor',
    'Fukuisaurus',
    'Fulgurotherium',
    'Futalognkosaurus',

    'Gallimimus',
    'Gargoyleosaurus',
    'Garudimimus',
    'Gasosaurus',
    'Gasparinisaura',
    'Gastonia',
    'Genyodectes',
    'Gideonmantellia',
    'Giganotosaurus',
    'Gigantoraptor',
    'Gigantspinosaurus',
    'Gilmoreosaurus',
    'Giraffatitan',
    'Glacialisaurus',
    'Gobiceratops',
    'Gobisaurus',
    'Gobivenator',
    'Gojirasaurus',
    'Gondwanatitan',
    'Gorgosaurus',
    'Goyocephale',
    'Graciliraptor',
    'Gryphoceratops',
    'Gryponyx',
    'Gryposaurus',
    'Guaibasaurus',
    'Guanlong',

    'Hadrosaurus',
    'Hagryphus',
    'Halticosaurus',
    'Haplocanthosaurus',
    'Haplocheirus',
    'Harpymimus',
    'Haya',
    'Herrerasaurus',
    'Hesperonychus',
    'Hesperosaurus',
    'Heterodontosaurus',
    'Hexing',
    'Hexinlusaurus',
    'Heyuannia',
    'Hippodraco',
    'Homalocephale',
    'Hongshanosaurus',
    'Hoplitosaurus',
    'Huabeisaurus',
    'Huanghetitan',
    'Huaxiagnathus',
    'Huaxiaosaurus',
    'Huayangosaurus',
    'Huehuecanauhtlus',
    'Hungarosaurus',
    'Huxleysaurus',
    'Hylaeosaurus',
    'Hypacrosaurus',
    'Hypselosaurus',
    'Hypselospinus',
    'Hypsibema',
    'Hypsilophodon',


    'Ichthyovenator',
    'Ignavusaurus',
    'Iguanacolossus',
    'Iguanodon',
    'Ilokelesia',
    'Incisivosaurus',
    'Indosuchus',
    'Ingenia',
    'Irritator',
    'Isanosaurus',
    'Isisaurus',

    'Jainosaurus',
    'Janenschia',
    'Jaxartosaurus',
    'Jeholosaurus',
    'Jeyawati',
    'Jianchangosaurus',
    'Jinfengopteryx',
    'Jingshanosaurus',
    'Jinzhousaurus',
    'Jobaria',
    'Judiceratops',
    'Juratyrant',
    'Juravenator',

    'Kaatedocus',
    'Kaijiangosaurus',
    'Kazaklambia',
    'Kentrosaurus',
    'Kerberosaurus',
    'Khaan',
    'Kileskus',
    'Kinnareemimus',
    'Kol',
    'Koreaceratops',
    'Koreanosaurus',
    'Kosmoceratops',
    'Kotasaurus',
    'Kritosaurus',
    'Kryptops',
    'Kukufeldia',
    'Kulindadromeus',
    'Kundurosaurus',

    'Labocania',
    'Lagosuchus',
    'Lambeosaurus',
    'Lamplughsaura',
    'Lanzhousaurus',
    'Laosaurus',
    'Lapparentosaurus',
    'Laquintasaura',
    'Latirhinus',
    'Leaellynasaura',
    'Leinkupal',
    'Leonerasaurus',
    'Leptoceratops',
    'Leshansaurus',
    'Lesothosaurus',
    'Lessemsaurus',
    'Lexovisaurus',
    'Leyesaurus',
    'Liaoceratops',
    'Liaoningosaurus',
    'Liliensternus',
    'Limaysaurus',

    'Limusaurus',
    'Linhenykus',
    'Linheraptor',
    'Linhevenato',

    'Lophorhothon',
    'Lophostropheus',
    'Loricatosaurus',
    'Lourinhanosaurus',
    'Lourinhasaurus',
    'Luanchuanraptor',
    'Lufengosaurus',
    'Lurdusaurus',
    'Lusotitan',
    'Lycorhinus',
    'Lythronax',


    'Machairasaurus',
    'Macrogryphosaurus',
    'Magnapaulia',
    'Magnirostris',
    'Magnosaurus',
    'Magyarosaurus',
    'Mahakala',
    'Maiasaura',
    'Majungasaurus',
    'Malawisaurus',
    'Mamenchisaurus',
    'Manidens',
    'Mantellisaurus',
    'Mantellodon',
    'Mapusaurus',
    'Marshosaurus',
    'Martharaptor',
    'Masiakasaurus',
    'Massospondylus',
    'Maxakalisaurus',
    'Medusaceratops',
    'Megalosaurus',
    'Megapnosaurus',
    'Megaraptor',
    'Mei',
    'Melanorosaurus',
    'Mendozasaurus',
    'Mercuriceratops',
    'Metriacanthosaurus',
    'Microceratops',
    'Micropachycephalosaurus',
    'Microraptor',
    'Microvenator',
    'Minmi',
    'Minotaurasaurus',
    'Miragaia',
    'Mirischia',
    'Mochlodon',
    'Mojoceratops',
    'Monkonosaurus',
    'Monoclonius',
    'Monolophosaurus',
    'Mononykus',
    'Montanoceratops',
    'Mussaurus',
    'Muttaburrasaurus',
    'Mymoorapelta',

    'Nankangia',
    'Nanosaurus',
    'Nanotyrannus',
    'Nanshiungosaurus',
    'Nanuqsaurus',
    'Nanyangosaurus',
    'Nasutoceratops',
    'Nebulasaurus',
    'Nedcolbertia',
    'Neimongosaurus',
    'Nemegtomaia',
    'Nemegtosaurus',
    'Neovenator',
    'Neuquenraptor',
    'Neuquensaurus',
    'Nigersaurus',
    'Nipponosaurus',
    'Noasaurus',
    'Nodocephalosaurus',
    'Nodosaurus',
    'Nomingia',
    'Nothronychus',
    'Notohypsilophodon',
    'Nqwebasaurus',
    'Nuthetes',
    'Nyasasaurus',

    'Ojoceratops',
    'Olorotitan',
    'Omeisaurus',
    'Oohkotokia',
    'Opisthocoelicaudia',
    'Orkoraptor',
    'Ornithodesmus',
    'Ornitholestes',
    'Ornithomimus',
    'Ornithopsis',
    'Orodromeus',
    'Orthomerus',
    'Oryctodromeus',
    'Ostafrikasaurus',
    'Othnielia',
    'Othnielosaurus',
    'Ouranosaurus',
    'Overosaurus',
    'Oviraptor',
    'Oxalaia',
    'Ozraptor',

    'Pachycephalosaurus',
    'Pachyrhinosaurus',
    'Palaeoscincus',
    'Paluxysaurus',
    'Pampadromaeus',
    'Pamparaptor',
    'Panamericansaurus',
    'Panoplosaurus',
    'Panphagia',
    'Pantydraco',
    'Paralititan',
    'Paranthodon',
    'Pararhabdodon',
    'Parasaurolophus',
    'Parksosaurus',
    'Paronychodon',
    'Parvicursor',
    'Patagosaurus',
    'Pawpawsaurus',
    'Pedopenna',
    'Pegomastax',
    'Pelecanimimus',
    'Peloroplites',
    'Pelorosaurus',
    'Pentaceratops',
    'Philovenator',
    'Phuwiangosaurus',
    'Piatnitzkysaurus',
    'Pinacosaurus',
    'Pisanosaurus',
    'Piveteausaurus',
    'Planicoxa',
    'Plateosaurus',
    'Pleurocoelus',
    'Pneumatoraptor',
    'Podokesaurus',
    'Poekilopleuron',
    'Polacanthus',
    'Prenocephale',
    'Prenoceratops',
    'Proa',
    'Probactrosaurus',
    'Proceratosaurus',
    'Procompsognathus',
    'Propanoplosaurus',
    'Prosaurolophus',
    'Protarchaeopteryx',
    'Protoceratops',
    'Protohadros',
    'Psittacosaurus',
    'Puertasaurus',
    'Pyroraptor',


    'Qantassaurus',
    'Qianzhousaurus',
    'Qiaowanlong',
    'Qiupalong',
    'Quaesitosaurus',
    'Quilmesaurus',

    'Rahiolisaurus',
    'Rahonavis',
    'Rajasaurus',
    'Rapator',
    'Rapetosaurus',
    'Raptorex',
    'Rebbachisaurus',
    'Regaliceratops',
    'Regnosaurus',
    'Rhabdodon',
    'Rhinorex',
    'Rhoetosaurus',
    'Richardoestesia',
    'Rinchenia',
    'Rinconsaurus',
    'Riojasaurus',
    'Rubeosaurus',
    'Rugops',

    'Sahaliyania',
    'Saichania',
    'Saltasaurus',
    'Saltopus',
    'Sanjuansaurus',
    'Santanaraptor',
    'Sarahsaurus',
    'Sarcolestes',
    'Sarcosaurus',
    'Saturnalia',
    'Saurolophus',
    'Sauroniops',
    'Sauropelta',
    'Saurophaganax',
    'Sauroposeidon',
    'Saurornithoides',
    'Saurornitholestes',
    'Savannasaurus',
    'Scansoriopteryx',
    'Scelidosaurus',
    'Scipionyx',
    'Sciurumimus',
    'Scolosaurus',
    'Scutellosaurus',
    'Secernosaurus',
    'Seitaad',
    'Segisaurus',
    'Segnosaurus',
    'Seismosaurus',
    'Sellosaurus',
    'Serendipaceratops',
    'Shamosaurus',
    'Shanag',
    'Shantungosaurus',
    'Shaochilong',
    'Shenzhousaurus',
    'Shunosaurus',
    'Shuvosaurus',
    'Shuvuuia',
    'Siamodon',
    'Siamosaurus',
    'Siamotyrannus',
    'Siats',
    'Sigilmassasaurus',
    'Silvisaurus',
    'Similicaudipteryx',
    'Sinocalliopteryx',
    'Sinoceratops',
    'Sinornithoides',
    'Sinornithomimus',
    'Sinornithosaurus',
    'Sinosauropteryx',
    'Sinosaurus',
    'Sinotyrannus',
    'Sinovenator',
    'Sinraptor',
    'Sinusonasus',
    'Skorpiovenator',
    'Sonorasaurus',
    'Sphaerotholus',
    'Spinophorosaurus',
    'Spinops',
    'Spinosaurus',
    'Spinostropheus',
    'Staurikosaurus',
    'Stegoceras',
    'Stegosaurus',
    'Stenopelix',
    'Stokesosaurus',
    'Struthiomimus',
    'Struthiosaurus',
    'Stygimoloch',
    'Styracosaurus',
    'Suchomimus',
    'Sulaimanisaurus',
    'Supersaurus',
    'Suuwassea',
    'Suzhousaurus',
    'Szechuanosaurus',

    'Tachiraptor',
    'Talarurus',
    'Talenkauen',
    'Talos',
    'Tangvayosaurus',
    'Tanius',
    'Tanycolagreus',
    'Taohelong',
    'Tapuiasaurus',
    'Tarascosaurus',
    'Tarbosaurus',
    'Tarchia',
    'Tastavinsaurus',
    'Tatankacephalus',
    'Tatankaceratops',
    'Tataouinea',
    'Tawa',
    'Tazoudasaurus',
    'Technosaurus',
    'Tehuelchesaurus',
    'Telmatosaurus',
    'Tendaguria',
    'Tenontosaurus',
    'Teratophoneus',
    'Tethyshadros',
    'Texacephale',
    'Thecocoelurus',
    'Thecodontosaurus',
    'Theiophytalia',
    'Therizinosaurus',
    'Thescelosaurus',
    'Tianchisaurus',
    'Tianyulong',

    'Tianyuraptor',
    'Tianzhenosaurus',
    'Timimus',
    'Titanoceratops',
    'Titanosaurus',
    'Tochisaurus',
    'Tornieria',
    'Torosaurus',
    'Torvosaurus',
    'Triceratops',
    'Trinisaura',
    'Troodon',
    'Tsaagan',
    'Tsintaosaurus',
    'Tuojiangosaurus',
    'Turanoceratops',
    'Turiasaurus',
    'Tylocephale',
    'Tyrannosaurus Rex',
    'Tyrannotitan',

    'Uberabatitan',
    'Udanoceratops',
    'Unaysaurus',
    'Unenlagia',
    'Unescoceratops',
    'Urbacodon',
    'Utahceratops',
    'Utahraptor',
    'Uteodon',

    'Vagaceratops',
    'Vahiny',
    'Valdoraptor',
    'Valdosaurus',
    'Variraptor',
    'Velafrons',
    'Velociraptor',
    'Velocisaurus',
    'Venenosaurus',
    'Veterupristisaurus',
    'Vulcanodon',

    'Wannanosaurus',
    'Wellnhoferia',
    'Wendiceratops',
    'Willinakaqe',
    'Wintonotitan',
    'Wuerhosaurus',
    'Wulagasaurus',

    'Xenoceratops',
    'Xenoposeidon',
    'Xenotarsosaurus',
    'Xiaosaurus',
    'Xiaotingia',
    'Xinjiangtitan',
    'Xiongguanlong',
    'Xixianykus',
    'Xuanhanosaurus',
    'Xuanhuaceratops',
    'Xuwulong',

    'Yamaceratops',
    'Yandusaurus',
    'Yangchuanosaurus',
    'Yaverlandia',
    'Yi Qi',
    'Yimenosaurus',
    'Yinlong',
    'Yixianosaurus',
    'Yizhousaurus',
    'Yongjinglong',
    'Yueosaurus',
    'Yulong',
    'Yunnanosaurus',
    'Yutyrannus',

    'Zalmoxes',
    'Zanabazar',
    'Zapalasaurus',
    'Zby',
    'Zephyrosaurus',
    'Zhanghenglong',
    'Zhejiangosaurus',
    'Zhenyuanlong',
    'Zhongyuansaurus',
    'Zhuchengceratops',
    'Zhuchengosaurus',
    'Zhuchengtyrannus',
    'Zuniceratops',
    'Zuolong',
    'Zupaysaurus'
  ];

  inspirations: Array<string> = [];

  constructor() { }

  ngOnInit(): void {
    this.inspirations = this.random();
  }

  random() {
    return [
      this.getRandom( this.animals ),
      this.getRandom( this.dinosaurs ),
      this.getRandom( this.foods ),
      (new RandomThingList()).getRandom(),
      (new MythicalCreatures()).getRandom(),
      ]
  }

  getRandom( arr: Array<string> ): string
  {
    return arr[Math.floor(Math.random() * arr.length)];
  }
}
